version: '3.9'
services:
  app: 
    container_name: 'ProgPa_Backend'
    build: .
    ports:
      - '3000:3000'

  db:
    container_name: 'ProgPa_Database'
    image: 'postgres'
    ports: 
      - '4321:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
